USE [master]
GO
/****** Object:  Database [TokeDemoDB]    Script Date: 7/22/2024 8:54:52 AM ******/
CREATE DATABASE [TokeDemoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TokeDemoDB', FILENAME = N'C:\SQLData\TokeDemoDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TokeDemoDB_log', FILENAME = N'C:\SQLData\TokeDemoDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TokeDemoDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TokeDemoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TokeDemoDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TokeDemoDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TokeDemoDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TokeDemoDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TokeDemoDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TokeDemoDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TokeDemoDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TokeDemoDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TokeDemoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TokeDemoDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TokeDemoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TokeDemoDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TokeDemoDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TokeDemoDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TokeDemoDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TokeDemoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TokeDemoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TokeDemoDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TokeDemoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TokeDemoDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TokeDemoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TokeDemoDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TokeDemoDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TokeDemoDB] SET  MULTI_USER 
GO
ALTER DATABASE [TokeDemoDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TokeDemoDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TokeDemoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TokeDemoDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TokeDemoDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TokeDemoDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TokeDemoDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [TokeDemoDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TokeDemoDB]
GO
/****** Object:  Table [dbo].[RefreshToken]    Script Date: 7/22/2024 8:54:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RefreshToken](
	[RefreshTokenId] [bigint] NOT NULL,
	[Token] [nvarchar](max) NOT NULL,
	[Jwt] [nvarchar](max) NOT NULL,
	[CreationDate] [datetime2](7) NOT NULL,
	[ExpiryDate] [datetime2](7) NOT NULL,
	[Used] [bit] NULL,
	[UserId] [bigint] NOT NULL,
 CONSTRAINT [PK_RefreshToken] PRIMARY KEY CLUSTERED 
(
	[RefreshTokenId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RolesMaster]    Script Date: 7/22/2024 8:54:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RolesMaster](
	[RoleId] [bigint] NOT NULL,
	[RoleName] [nvarchar](256) NOT NULL,
	[CreatedOn] [datetime2](7) NOT NULL,
	[UpdatedOn] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_RolesMaster] PRIMARY KEY CLUSTERED 
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserMaster]    Script Date: 7/22/2024 8:54:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserMaster](
	[UserId] [bigint] NOT NULL,
	[FirstName] [nvarchar](256) NOT NULL,
	[LastName] [nvarchar](256) NOT NULL,
	[UserName] [nvarchar](256) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](256) NOT NULL,
	[PhoneNumber] [nvarchar](max) NOT NULL,
	[CreatedOn] [datetime2](7) NOT NULL,
	[UpdatedOn] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_UserMaster] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserRoles]    Script Date: 7/22/2024 8:54:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRoles](
	[UserId] [bigint] NOT NULL,
	[RoleId] [bigint] NOT NULL,
 CONSTRAINT [PK_UserRoles] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RefreshToken]  WITH CHECK ADD  CONSTRAINT [FK_RefreshToken_UserMaster] FOREIGN KEY([UserId])
REFERENCES [dbo].[UserMaster] ([UserId])
GO
ALTER TABLE [dbo].[RefreshToken] CHECK CONSTRAINT [FK_RefreshToken_UserMaster]
GO
ALTER TABLE [dbo].[UserRoles]  WITH CHECK ADD  CONSTRAINT [FK_UserRoles_RolesMaster] FOREIGN KEY([RoleId])
REFERENCES [dbo].[RolesMaster] ([RoleId])
GO
ALTER TABLE [dbo].[UserRoles] CHECK CONSTRAINT [FK_UserRoles_RolesMaster]
GO
ALTER TABLE [dbo].[UserRoles]  WITH CHECK ADD  CONSTRAINT [FK_UserRoles_UserMaster] FOREIGN KEY([UserId])
REFERENCES [dbo].[UserMaster] ([UserId])
GO
ALTER TABLE [dbo].[UserRoles] CHECK CONSTRAINT [FK_UserRoles_UserMaster]
GO
USE [master]
GO
ALTER DATABASE [TokeDemoDB] SET  READ_WRITE 
GO
