USE [master]
GO
/****** Object:  Database [TokeDemoDB]    Script Date: 7/22/2024 4:13:30 PM ******/
CREATE DATABASE [TokeDemoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TokeDemoDB', FILENAME = N'C:\SQLData\TokeDemoDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TokeDemoDB_log', FILENAME = N'C:\SQLData\TokeDemoDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TokeDemoDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TokeDemoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TokeDemoDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TokeDemoDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TokeDemoDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TokeDemoDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TokeDemoDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TokeDemoDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TokeDemoDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TokeDemoDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TokeDemoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TokeDemoDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TokeDemoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TokeDemoDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TokeDemoDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TokeDemoDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TokeDemoDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TokeDemoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TokeDemoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TokeDemoDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TokeDemoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TokeDemoDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TokeDemoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TokeDemoDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TokeDemoDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TokeDemoDB] SET  MULTI_USER 
GO
ALTER DATABASE [TokeDemoDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TokeDemoDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TokeDemoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TokeDemoDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TokeDemoDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TokeDemoDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TokeDemoDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [TokeDemoDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TokeDemoDB]
GO
/****** Object:  Table [dbo].[RefreshToken]    Script Date: 7/22/2024 4:13:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RefreshToken](
	[RefreshTokenId] [bigint] IDENTITY(1,1) NOT NULL,
	[Token] [nvarchar](max) NOT NULL,
	[JwtId] [nvarchar](max) NOT NULL,
	[CreationDate] [datetime2](7) NOT NULL,
	[ExpiryDate] [datetime2](7) NOT NULL,
	[Used] [bit] NULL,
	[UserId] [bigint] NOT NULL,
 CONSTRAINT [PK_RefreshToken] PRIMARY KEY CLUSTERED 
(
	[RefreshTokenId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RolesMaster]    Script Date: 7/22/2024 4:13:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RolesMaster](
	[RoleId] [bigint] IDENTITY(1,1) NOT NULL,
	[RoleName] [nvarchar](256) NOT NULL,
	[CreatedOn] [datetime2](7) NOT NULL,
	[UpdatedOn] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_RolesMaster] PRIMARY KEY CLUSTERED 
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserRoles]    Script Date: 7/22/2024 4:13:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRoles](
	[UserRoleId] [bigint] IDENTITY(1,1) NOT NULL,
	[UserId] [bigint] NOT NULL,
	[RoleId] [bigint] NOT NULL,
 CONSTRAINT [PK_UserRoles] PRIMARY KEY CLUSTERED 
(
	[UserRoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UsersMaster]    Script Date: 7/22/2024 4:13:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UsersMaster](
	[UserId] [bigint] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](256) NOT NULL,
	[LastName] [nvarchar](256) NOT NULL,
	[UserName] [nvarchar](256) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](256) NOT NULL,
	[PhoneNumber] [nvarchar](max) NOT NULL,
	[CreatedOn] [datetime2](7) NOT NULL,
	[UpdatedOn] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_UserMaster] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[RolesMaster] ON 
GO
INSERT [dbo].[RolesMaster] ([RoleId], [RoleName], [CreatedOn], [UpdatedOn]) VALUES (1, N'Admin', CAST(N'2024-07-22T10:55:07.5533333' AS DateTime2), CAST(N'2024-07-22T10:55:07.5533333' AS DateTime2))
GO
INSERT [dbo].[RolesMaster] ([RoleId], [RoleName], [CreatedOn], [UpdatedOn]) VALUES (2, N'Staff', CAST(N'2024-07-22T11:19:28.7366667' AS DateTime2), CAST(N'2024-07-22T11:19:28.7366667' AS DateTime2))
GO
SET IDENTITY_INSERT [dbo].[RolesMaster] OFF
GO
SET IDENTITY_INSERT [dbo].[UserRoles] ON 
GO
INSERT [dbo].[UserRoles] ([UserRoleId], [UserId], [RoleId]) VALUES (1, 1, 1)
GO
INSERT [dbo].[UserRoles] ([UserRoleId], [UserId], [RoleId]) VALUES (2, 1, 2)
GO
INSERT [dbo].[UserRoles] ([UserRoleId], [UserId], [RoleId]) VALUES (3, 2, 2)
GO
SET IDENTITY_INSERT [dbo].[UserRoles] OFF
GO
SET IDENTITY_INSERT [dbo].[UsersMaster] ON 
GO
INSERT [dbo].[UsersMaster] ([UserId], [FirstName], [LastName], [UserName], [Password], [Email], [PhoneNumber], [CreatedOn], [UpdatedOn]) VALUES (1, N'Thuan', N'Tran', N'thuantv', N'abcd1234', N'tvt.iot@gmail.com', N'84984576803', CAST(N'2024-07-22T11:18:08.0200000' AS DateTime2), CAST(N'2024-07-22T11:18:08.0200000' AS DateTime2))
GO
INSERT [dbo].[UsersMaster] ([UserId], [FirstName], [LastName], [UserName], [Password], [Email], [PhoneNumber], [CreatedOn], [UpdatedOn]) VALUES (2, N'Hung', N'Tran', N'shanetran', N'abcd1234', N'shanevt@gmail.com', N'84941198368', CAST(N'2024-07-22T11:19:00.6600000' AS DateTime2), CAST(N'2024-07-22T11:19:00.6600000' AS DateTime2))
GO
SET IDENTITY_INSERT [dbo].[UsersMaster] OFF
GO
ALTER TABLE [dbo].[RolesMaster] ADD  CONSTRAINT [DF_RolesMaster_CreatedOn]  DEFAULT (getdate()) FOR [CreatedOn]
GO
ALTER TABLE [dbo].[RolesMaster] ADD  CONSTRAINT [DF_RolesMaster_UpdatedOn]  DEFAULT (getdate()) FOR [UpdatedOn]
GO
ALTER TABLE [dbo].[UsersMaster] ADD  CONSTRAINT [DF_UserMaster_CreatedOn]  DEFAULT (getdate()) FOR [CreatedOn]
GO
ALTER TABLE [dbo].[UsersMaster] ADD  CONSTRAINT [DF_UserMaster_UpdatedOn]  DEFAULT (getdate()) FOR [UpdatedOn]
GO
ALTER TABLE [dbo].[RefreshToken]  WITH CHECK ADD  CONSTRAINT [FK_RefreshToken_UsersMaster] FOREIGN KEY([UserId])
REFERENCES [dbo].[UsersMaster] ([UserId])
GO
ALTER TABLE [dbo].[RefreshToken] CHECK CONSTRAINT [FK_RefreshToken_UsersMaster]
GO
ALTER TABLE [dbo].[UserRoles]  WITH CHECK ADD  CONSTRAINT [FK_UserRoles_RolesMaster] FOREIGN KEY([RoleId])
REFERENCES [dbo].[RolesMaster] ([RoleId])
GO
ALTER TABLE [dbo].[UserRoles] CHECK CONSTRAINT [FK_UserRoles_RolesMaster]
GO
ALTER TABLE [dbo].[UserRoles]  WITH CHECK ADD  CONSTRAINT [FK_UserRoles_UsersMaster] FOREIGN KEY([UserId])
REFERENCES [dbo].[UsersMaster] ([UserId])
GO
ALTER TABLE [dbo].[UserRoles] CHECK CONSTRAINT [FK_UserRoles_UsersMaster]
GO
USE [master]
GO
ALTER DATABASE [TokeDemoDB] SET  READ_WRITE 
GO
